### PR TITLE
Bump version of aws-config

### PR DESCRIPTION
**Pull request by landonxjames**
## Motivation and Context

At some point during the long lifetime of https://github.com/smithy-lang/smithy-rs/pull/4721, the version of `aws-config` in main caught up (or passed) the version in the PR and it never got bumped again. The only change we needed was for `aws-config` to bump its dependency version on `aws-smithy-json`, so the runtime version checks didn't catch that there was a change and `aws-config` was not released with the rest of the breaking changes yesterday. 

Some server crates were also still pulling in `aws-smithy-json` `0.63`

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: .changelog/breaking-change-bumps.md [hunk 1]
```diff
@@ -0,0 +1,10 @@
+# ---
+# applies_to: ["client", "server", "aws-sdk-rust"]
+# authors: ["landonxjames"]
+# references: ["smithy-rs#920"]
```
Comment (ysaito1001) [inline .changelog/breaking-change-bumps.md]: Is this referring to https://github.com/smithy-lang/smithy-rs/pull/920 ?

**Review by ysaito1001 — APPROVED** [review]

File: .changelog/breaking-change-bumps.md (hunk 1 above)
Comment (landonxjames) [reply .changelog/breaking-change-bumps.md]: Good catch, updated to point to 4853 in https://github.com/smithy-lang/smithy-rs/pull/4854/commits/81f7a65d2f0fc17c699a7a8bb7e665d21971b8c8

**Review by lauzadis — COMMENTED** [review]
I think we also need to bump aws-types to 1.6.1 so that it's re-released with a dependency on aws-smithy-schema 0.3.0.

https://crates.io/crates/aws-types/1.6.0/dependencies

**Review by lauzadis — DISMISSED** [review]

**Comment by drganjoo** [comment]
> I think we also need to bump aws-types to 1.6.1 so that it's re-released with a dependency on aws-smithy-schema 0.3.0.
> https://crates.io/crates/aws-types/1.6.0/dependencies

Since `aws-smithy-types` is `1.x`, that will need to be bumped to `2.x` if it continues to have breaking API changes.

Cargo.toml:

```toml
[package]
name = "check-ver"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-smithy-json = "=0.63.0"
aws-smithy-types = "1.6.1"
```

Cargo will pick up `1.7.x` as it is semver compatible with `1.6.1`.  However, `aws-smithy-json` doesn't work with `aws-smithy-types` @ `1.7.x`.

Error:

```
error[E0004]: non-exhaustive patterns: `&_` not covered
  --> /home/fahadzub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-smithy-json-0.63.0/src/serialize.rs:36:15
   |
36 |         match value {
   |               ^^^^^ pattern `&_` not covered
   |
note: `aws_smithy_types::Document` defined here
  --> /home/fahadzub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-smithy-types-1.7.0/src/document/mod.rs:91:1
   |
91 | pub enum Document {
   | ^^^^^^^^^^^^^^^^^
   = note: the matched value is of type `&aws_smithy_types::Document`
   = note: `aws_smithy_types::Document` is marked as non-exhaustive, so a wildcard `_` is necessary to match exhaustively
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
   |
54 ~             Document::String(value) => self.string(value),
55 ~             &_ => todo!(),
   |

Some errors have detailed explanations: E0004, E0308.
For more information about an error, try `rustc --explain E0004`.
error: could not compile `aws-smithy-json` (lib) due to 3 previous errors
```
