### ISSUE TITLE
aws-runtime event-stream SigV4 signer fails to compile with Rust 1.94.1 (E0282)

### ISSUE THREAD

**Issue by kent8192** [smithy-lang/smithy-rs#4696]
### Summary

`aws-runtime` fails to compile on Rust 1.94.1 when the `event-stream` feature is enabled. The failure is in `aws-runtime/src/auth/sigv4.rs` where the event stream signer is sent with `as _`, and rustc can no longer infer the erased trait-object type.

This currently affects downstream crates such as `aws-sdk-s3`, which depends on `aws-runtime` with `event-stream` enabled.

### Minimal reproduction

```toml
[package]
name = "aws-runtime-repro"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
aws-runtime = { version = "=1.7.4", features = ["event-stream", "http-02x", "http-1x", "sigv4a"] }
```

```rust
pub fn repro_anchor() {}
```

Run:

```bash
cargo +1.94.1 check
```

### Actual result

```text
error[E0282]: type annotations needed
   --> .../aws-runtime-1.7.4/src/auth/sigv4.rs:278:22
    |
278 |                     .send(Box::new(SigV4MessageSigner::new(
    |                      ^^^^ cannot infer type of the type parameter `T` declared on the method `send`
...
285 |                     )) as _)
    |                           - type must be known at this point
```

### Expected result

`aws-runtime` should compile with `event-stream` enabled on its declared supported Rust range.

### Environment

- `rustc 1.94.1 (e408947bf 2026-03-25)`
- macOS aarch64 locally
- Also reproduced on GitHub Actions Ubuntu 24.04 with Rust 1.94.1 while compiling `aws-sdk-s3` via `aws-runtime 1.7.4`

### Likely fix

The ambiguous cast appears to be this expression:

```rust
.send(Box::new(SigV4MessageSigner::new(...)) as _)
```

Using the explicit trait-object type expected by `DeferredSignerSender::send`, such as `Box<dyn SignMessage + Send + Sync>`, should avoid the inference failure.

**Comment by ysaito1001** [comment]
We're working on to get `aws-runtime` 1.7.5 out as soon as possible (the release was blocked in the morning due to the `time` crate [issue](https://github.com/time-rs/time/issues/783)).

Once it's available on crates.io, the command
```
cargo clean && cargo run
```
should upgrade
- aws-smithy-types -> 1.5.0 (already published)
- aws-smithy-eventstream -> 0.60.21 (already published)
- aws-runtime -> 1.7.5 (~working on releasing this to crates.io~  published)

P.S.
aws-runtime 1.7.5 has been [published](https://crates.io/crates/aws-runtime/1.7.5).

The clean build above should resolve the error (may need to pin `time` crate to 0.3.47). Please let us know if you run into any further issues.

**Comment by ysaito1001** [comment]
Should be fixed by https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2026-06-12

Please let us know if you run into any further issues.
